name: Snyk Security Vulnerability Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

permissions:
  contents: read

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Check changed Deps files
        uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          files: | # This will match all the files with below patterns
            Pipfile
    
      - name: Scan python dependencies
        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, 'Pipfile')
        env:
          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
        run: |
          make setup
          sed -n '/\[dev-packages\]/q;p' Pipfile > temp.txt && mv temp.txt Pipfile
          snyk test \
            -d \
            --file=Pipfile \
            --command=python3.10 \
            --skip-unresolved \
            --severity-threshold=high
     
  snyk_scan_monitor:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master

      - name: Extract github branch/tag name
        shell: bash
        run: echo "ref=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_ref

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Monitor python dependencies
        env:
          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
        run: |
          make setup
          sed -n '/\[dev-packages\]/q;p' Pipfile > temp.txt && mv temp.txt Pipfile
          snyk monitor \
            -d \
            --file=Pipfile \
            --command=python3.10 \
            --skip-unresolved \
            --remote-repo-url=h2o-llm-studio/${{ steps.extract_ref.outputs.ref }} \
            --org=h2o-llm-studio \
            --project-name=H2O-LLM-STUDIO/h2o-llm-studio/${{ steps.extract_ref.outputs.ref }}/Pipfile
